### PR TITLE
Vulnerabilities SDK guide in progress

### PR DESCRIPTION
**Pull request by jclark-vmware**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [x] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [x] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x] A self-review of the code has been done.

## What is the ticket or issue number?

https://jira.carbonblack.local/browse/CBAPI-3118

## Pull Request Description

In progress draft of SDK guide for Vulnerabilities

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by lhilmes-cb — APPROVED** [review]
Looks great to me!

**Review by avanbrunt-cb — COMMENTED** [review]
I would recommend using a similar output style and provide a sample output similar to what Amy did for the Watchlist guide. You made need to implement the `def _subobject` function for the Vulnerability Class in order to take advantage of the special printing

https://github.com/carbonblack/carbon-black-cloud-sdk-python/pull/223

**Review by avanbrunt-cb — APPROVED** [review]
You can merge now if needed otherwise Amy is working on a modification so you can use the pretty print for the Vulnerability object instead of need to build a custom print statement

**Review by avanbrunt-cb — APPROVED** [review]

**Review by abowersox-cb — APPROVED** [review]
NIcely done! And the new formatted objects look great, if I do say so myself.

**Review by avanbrunt-cb — APPROVED** [review]

**Review by lhilmes-cb — APPROVED** [review]
Looks great!

**Pull request merged**
