### PR TITLE
CBAPI-2606: Receive enum in upper or lower case

### PR DESCRIPTION
**Pull request by emitreva-cb**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] Docs have been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Tests have been added that prove the fix is effective or that the feature works.
- [x] New and existing tests pass locally with the changes.
- [x] Code follows the style guidelines of this project (PEP8, clean code, linter).
- [x] A self-review of the code has been done.

## What is the ticket or issue number?
https://jira.carbonblack.local/browse/CBAPI-2606

## Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by avanbrunt-cb — APPROVED** [review]

**Review by kebringer-cb — COMMENTED** [review]
There is also a status of "CANCELLED".  Does this to be listed or handled specifically?
https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/live-response-api/#cancel-command

**Review by abowersox-cb — COMMENTED** [review]
Test cases should use a mixture of lower-case and upper-case statuses, to ensure that the code will work even after the underlying endpoint is fixed.

**Review by mrangelov-cb — APPROVED** [review]

**Review by abowersox-cb — APPROVED** [review]
Reviewed during Kaffee Klatsch and feedback was applied.

**Comment by emitreva-cb** [comment]
> There is also a status of "CANCELLED". Does this to be listed or handled specifically?
> https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/live-response-api/#cancel-command

It doesn't seem to be used anywhere in the live response in the SDK.

**Comment by avanbrunt-cb** [comment]
> > There is also a status of "CANCELLED". Does this to be listed or handled specifically?
> > https://developer.carbonblack.com/reference/carbon-black-cloud/platform/latest/live-response-api/#cancel-command
> 
> It doesn't seem to be used anywhere in the live response in the SDK.

You would use this in a PUT to the command to change the status to CANCELLED in order to terminate a command early. We might want to consider adding a terminate or cancel command function

**Pull request merged**
